name: Verify build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  STRAPI_REST_READONLY_API_KEY: random-value-just-for-build

jobs:
  lint:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest 
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: '${{ runner.os }}-turbo-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Prepare Environment Variables
        run: |
          cp apps/strapi/.env.example apps/strapi/.env
          cp apps/web/.env.local.example apps/web/.env.local

      - name: pnpm format:check
        run: pnpm format:check

      - name: pnpm lint
        run: pnpm lint

  build:
    name: Build all apps
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: '${{ runner.os }}-turbo-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
      
      - name: Prepare Environment Variables
        run: |
          cp apps/strapi/.env.example apps/strapi/.env
          cp apps/web/.env.local.example apps/web/.env.local

      - name: Build UI
        run: pnpm build:web

      - name: Build Strapi
        run: pnpm build:strapi
